# Generated by Django 3.0.4 on 2020-03-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.CharField(max_length=50)),
                ('hora_fim', models.CharField(max_length=50)),
                ('intervalo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=0)),
                ('tipo', models.CharField(max_length=20)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irriga.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50)),
                ('data_hora', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('sensores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irriga.Sensores')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irriga.Usuario')),
            ],
        ),
    ]
